
#this script tells polybar the status of the vpn. it uses a combination of the output of protonvpn-cli and a text file generated by vpn.sh to determine what the status is


server=$( protonvpn-cli s | grep 'Server:' | sed 's/.* //' )
connect=$( cat /tmp/vpn.txt 2>/dev/null)




if [[ $connect = "connecting" ]]
then
	
	if [[ $server = "" ]]
	then
		echo 'connecting'
	else
		echo 'connected to '$server
	fi
else
	echo 'not connected'
fi
